name = "crawl-radioswedenpalattsvenska"
main = "src/index.js"
compatibility_date = "2024-08-15"
workers_dev = true

[triggers]
crons = ["0 */3 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "lass"
database_id = "5539ba3d-983e-456f-8814-cd3f2442bf1d"
